server:
  servlet.context-path: /api/assembleia
  port: 8080

spring:
  application.name: assembleia-api
  cloud.config.fail-fast: true
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    deserialization.fail-on-unknown-properties: false
    default-property-inclusion: NON_ABSENT

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/assembleia?allowPublicKeyRetrieval=true&sslMode=DISABLED

  rabbitmq:
    port: 5672
    username: admin
    password: admin

logging:
  level:
    org.springframework.data: ERROR
    br.medeiros.guilherme.testesouth: DEBUG
    org.hibernate: ERROR

management:
  endpoint:
    liquibase:
      enabled: true

api:
  base: 'https://user-info.herokuapp.com'
  cpf: '/users/{cpf}'





