version: '3'

services:
  mysql:
    image: library/mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: assembleia
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mysqldb: